import react from "@vitejs/plugin-react"
import { defineConfig } from "vite-plus"

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "happy-dom",
    setupFiles: ["./happydom.ts", "./testing-library.ts", "./test/setupTests.ts"],
    include: ["src/**/*.test.{ts,tsx}", "test/**/*.test.{ts,tsx}", "postcss/**/*.test.{js,mjs,ts}"],
  },
  lint: {
    plugins: ["typescript", "react"],
    categories: {
      correctness: "off",
    },
    env: {
      builtin: true,
    },
    rules: {},
    overrides: [
      {
        files: ["**/*.{ts,tsx}"],
        rules: {
          "constructor-super": "off",
          "for-direction": "error",
          "getter-return": "off",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "off",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-const-assign": "off",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-class-members": "off",
          "no-dupe-else-if": "error",
          "no-dupe-keys": "off",
          "no-duplicate-case": "error",
          "no-empty": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-func-assign": "off",
          "no-global-assign": "error",
          "no-import-assign": "off",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-new-native-nonconstructor": "off",
          "no-nonoctal-decimal-escape": "error",
          "no-obj-calls": "off",
          "no-prototype-builtins": "error",
          "no-redeclare": "off",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-setter-return": "off",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-this-before-super": "off",
          "no-unreachable": "off",
          "no-unsafe-finally": "error",
          "no-unsafe-negation": "off",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-unused-vars": [
            "error",
            {
              args: "after-used",
              argsIgnorePattern: "^_",
              caughtErrors: "none",
              destructuredArrayIgnorePattern: "^_",
              varsIgnorePattern: "^_",
              ignoreRestSiblings: true,
            },
          ],
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-with": "off",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "no-var": "error",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
          "no-array-constructor": "error",
          "no-unused-expressions": [
            "error",
            {
              allowShortCircuit: true,
              allowTernary: true,
              allowTaggedTemplates: true,
            },
          ],
          "typescript/ban-ts-comment": "error",
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-empty-object-type": "error",
          "typescript/no-explicit-any": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": [
            "error",
            {
              allowDeclarations: true,
            },
          ],
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-require-imports": "error",
          "typescript/no-this-alias": "error",
          "typescript/no-unnecessary-type-constraint": "error",
          "typescript/no-unsafe-declaration-merging": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-namespace-keyword": "error",
          "typescript/triple-slash-reference": [
            "error",
            {
              path: "always",
            },
          ],
          "no-shadow": "error",
          "object-shorthand": "error",
          "path/no-absolute-imports": "error",
          "no-restricted-imports": [
            "error",
            {
              patterns: ["src/**", "@/**"],
            },
          ],
          "react/jsx-boolean-value": ["error", "never"],
          "react/forbid-elements": [
            "error",
            {
              forbid: [
                {
                  element: "b",
                  message: "Use <strong> instead of <b> for better semantics.",
                },
                {
                  element: "i",
                  message: "Use <em> instead of <i> for better semantics.",
                },
              ],
            },
          ],
          "react/jsx-curly-brace-presence": [
            "error",
            {
              props: "never",
            },
          ],
          "react/jsx-no-useless-fragment": [
            "error",
            {
              allowExpressions: true,
            },
          ],
          "no-console": "error",
          "react/rules-of-hooks": "error",
          "react/exhaustive-deps": "error",
          "react/only-export-components": [
            "warn",
            {
              allowConstantExport: true,
            },
          ],
        },
        env: {
          browser: true,
          es2022: true,
        },
      },
      {
        files: ["**/*.stories.{ts,tsx}", "scripts/**/*.{ts,tsx}"],
        rules: {
          "no-console": "off",
        },
      },
    ],
    jsPlugins: ["eslint-plugin-path"],
  },
  fmt: {
    printWidth: 100,
    quoteProps: "consistent",
    semi: false,
    tabWidth: 2,
    sortPackageJson: false,
    sortImports: {
      newlinesBetween: false,
      partitionByNewline: true,
      partitionByComment: true,
      groups: [
        ["builtin", "external", "internal", "subpath", "unknown"],
        ["parent", "sibling", "index", "style"],
      ],
    },
    sortTailwindcss: {
      stylesheet: "./src/styles/index.css",
      functions: ["clsx"],
    },
    ignorePatterns: ["*.mdx"],
  },
})
